### ISSUE TITLE
Set up tests on AppVeyor

### ISSUE THREAD

**Issue by rgbkrk** [nteract/jupyter-paths#11]
Yay for automated Windows testing.

**Comment by rgbkrk** [comment]
If you want an example of a far better API, check out https://github.com/nteract/ipython-paths. I wrote that one more holistically to adhere to the IPython specs (instead of directly porting the Python code).

**Comment by jdfreder** [comment]
I was interested in using appveryor for /nteract builds too

**Comment by rgbkrk** [comment]
This is pretty low hanging, might be good to start here. :smile:
