### ISSUE TITLE
When Python is not available, don't run the sys.prefix check

### ISSUE THREAD

**Issue by rgbkrk** [nteract/jupyter-paths#16]
Running nteract on a box without Python will fail on startup when it's ok for Python not to be on the system.

**Comment by minrk** [comment]
what does `sys-prefix-promise` return when there's no Python?

**Comment by minrk** [comment]
Either #20 or #21 should fix this.

**Comment by rgbkrk** [comment]
I should have captured the screen but on a fresh windows machine it showed a dialog for being unable to spawn python as a child process.
