### ISSUE TITLE
Can't resolve 'child_process'

### ISSUE THREAD

**Issue by sanjitgrover** [nteract/jupyter-paths#36]
I installed jupyter-paths using: npm i jupyter-paths,
and I am getting error - Can't resolve 'child_process' at ~node_modules\jupyter-paths when I am linking my extension using: jupyter labextension link .

My extension is built in Typescript.

I have tried many options available on Google - 
1. installing child_process and @types/node
2.  In package.json added - "browser": {
    "child_process": false
  }
3. In tsconfig.json added - "typeRoots": [
      "./node_modules/@types"
    ],
But nothing succeeded. Please help. This is the complete log:
$ jlpm run build:dev
$ jlpm run build
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in 'c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\jupyter-paths'
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:925:10
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\neo-async\async.js:2830:7
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\neo-async\async.js:6877:13
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:184:12
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\forEachBail.js:30:14
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (c:\Users\sanjit.grover\AppData\Local\Programs\Python\Python37\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
resolve 'child_process' in 'c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\jupyter-paths'
  Parsed request is a module
  using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\jupyter-paths\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\jupyter-paths\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\python37\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\python\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\programs\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\local\node_modules doesn't exist or is not a directory
      c:\users\sanjit.grover\appdata\node_modules doesn't exist or is not a directory
      c:\users\node_modules doesn't exist or is not a directory
      c:\node_modules doesn't exist or is not a directory
      looking for modules in c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules
        using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
      looking for modules in c:\users\sanjit.grover\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
              c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process is not a file
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
          c:\users\sanjit.grover\node_modules\child_process doesn't exist
        .wasm
          Field 'browser' doesn't contain a valid alias configuration
              c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process.json doesn't exist
          c:\users\sanjit.grover\node_modules\child_process.wasm doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
            as directory
              existing directory
                use ./index.js from main in package.json
                  using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\package.json (relative path: .)
                    Field 'browser' doesn't contain a valid alias configuration
          c:\users\sanjit.grover\node_modules\child_process.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
                    using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\package.json (relative path: ./index.js)
                      no extension
                        Field 'browser' doesn't contain a valid alias configuration
          c:\users\sanjit.grover\node_modules\child_process.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js doesn't exist
                      .wasm
                        Field 'browser' doesn't contain a valid alias configuration
          c:\users\sanjit.grover\node_modules\child_process.json doesn't exist
        as directory
          c:\users\sanjit.grover\node_modules\child_process doesn't exist
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js.wasm doesn't exist
                      .mjs
                        Field 'browser' doesn't contain a valid alias configuration
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js.mjs doesn't exist
                      .js
                        Field 'browser' doesn't contain a valid alias configuration
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js.js doesn't exist
                      .json
                        Field 'browser' doesn't contain a valid alias configuration
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js.json doesn't exist
                      as directory
                        c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js doesn't exist
                using path: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index
                  using description file: c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index doesn't exist
                    .wasm
                      Field 'browser' doesn't contain a valid alias configuration
                      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.wasm doesn't exist
                    .mjs
                      Field 'browser' doesn't contain a valid alias configuration
                      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.mjs doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      c:\users\sanjit.grover\appdata\local\programs\python\python37\share\jupyter\lab\staging\node_modules\child_process\index.json doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "c:\users\sanjit.grover\appdata\local\programs\python\python37\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\users\sanjit.grover\appdata\local\programs\python\python37\lib\site-packages\jupyterlab\labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "c:\users\sanjit.grover\appdata\local\programs\python\python37\lib\site-packages\jupyterlab\commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "c:\users\sanjit.grover\appdata\local\programs\python\python37\lib\site-packages\jupyterlab\commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by captainsafia** [comment]
@sanjitgrover This package is intended to be used in Node environments. The error you are running into is because you're attempting to use jupyter-paths inside a labextension, which run in the browser.

What are you trying to use the package for?

**Comment by aminya** [comment]
Yes, please use Nodejs. This code doesn't need Webpack as it is a single file.
