### ISSUE TITLE
Use the implementation in Hydrogen

### ISSUE THREAD

**Issue by n-riesco** [nteract/jupyter-paths#4]
I'm planning to add the flag `--ijs-install=hydrogen` to [IJavascript](http://n-riesco.github.io/ijavascript) so that it's possible to install the IJavascript kernel to one of the locations searched by [Hydrogen](https://github.com/willwhitney/hydrogen).

To this end, I'm looking for a npm package that provides the functionality in `jupyter-paths` without requiring the installation of `jupyter` or `ipython`.

Hydrogen already does that [here](https://github.com/willwhitney/hydrogen/blob/master/lib/paths.coffee). I think it'd be great if that code in Hydrogen was moved into this repository.

**Comment by rgbkrk** [comment]
Heh, I wrote that code in Hydrogen but opted to make this one only Jupyter. I'm happy to add on only IPython paths but there's a lot of legacy kludge which I wasn't sure we had to bring over (mostly Windows related - "is this for XP or prior?")

**Comment by n-riesco** [comment]
For my needs, jupyter-only paths are fine; issue #2, though, is also requesting support for IPython.

Currently, IJavascript depends on IPython/Jupyter to install its kernel. Hydrogen can run kernels on machines where Jupyter hasn't been installed. I would like to be able to install the IJavascript kernel on those machines too.

**Comment by rgbkrk** [comment]
Hey @n-riesco, sorry I had not come back to this again. I put together ipython-paths to handle the old IPython paths.

Taking a step back though, are you asking for jupyter-paths to not rely on Python directly for pathing? I'd like to move `jupyter-paths` back to that and not shell out. What do you think?

**Comment by rgbkrk** [comment]
All set and done.
